# Generated by Django 2.2.7 on 2019-11-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
